import { sql } from "drizzle-orm";
import { bigint, boolean, check, date, foreignKey, index, integer, jsonb, pgEnum, pgTable, text, time, timestamp, unique } from "drizzle-orm/pg-core";

// ============================================================================
// ENUMS - Added manually (introspection doesn't detect enums)
// ============================================================================

export const equipmentStatus = pgEnum("equipment_status", [
	"available",
	"in_use",
	"maintenance",
	"out_of_order",
	"retired",
]);

export const formStatus = pgEnum("form_status", ["draft", "published", "archived"]);

export const userRole = pgEnum("user_role", ["admin", "scientist", "student", "tech", "viewer"]);

export const laboratoryStatus = pgEnum("laboratory_status", ["available", "in_use", "under_maintenance", "decommissioned"]);

// ============================================================================
// TABLES - Generated by Drizzle introspection
// ============================================================================

export const equipment = pgTable("equipment", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "equipment_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	name: text().notNull(),
	type: text(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	laboratoryId: bigint("laboratory_id", { mode: "number" }).notNull(),
	status: text().default('available').notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("equipment_laboratory_id_idx").using("btree", table.laboratoryId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.laboratoryId],
			foreignColumns: [laboratories.id],
			name: "equipment_laboratory_id_fkey"
		}),
]);

export const experiments = pgTable("experiments", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "experiments_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	name: text().notNull(),
	description: text(),
	startDate: date("start_date"),
	endDate: date("end_date"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	laboratoryId: bigint("laboratory_id", { mode: "number" }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("experiments_laboratory_id_idx").using("btree", table.laboratoryId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.laboratoryId],
			foreignColumns: [laboratories.id],
			name: "experiments_laboratory_id_fkey"
		}),
	check("experiments_date_consistency", sql`(end_date IS NULL) OR (start_date IS NULL) OR (end_date >= start_date)`),
]);

export const formTemplateVersions = pgTable("form_template_versions", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "form_template_versions_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	formTemplateId: bigint("form_template_id", { mode: "number" }).notNull(),
	version: integer().notNull(),
	structure: jsonb().notNull(),
	modifiedAt: timestamp("modified_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("ftv_form_template_id_idx").using("btree", table.formTemplateId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.formTemplateId],
			foreignColumns: [formTemplates.id],
			name: "form_template_versions_form_template_id_fkey"
		}).onDelete("cascade"),
	unique("form_template_versions_unique").on(table.formTemplateId, table.version),
]);

export const formTemplates = pgTable("form_templates", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "form_templates_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	name: text().notNull(),
	description: text(),
	structure: jsonb().notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	createdBy: bigint("created_by", { mode: "number" }),
}, (table) => [
	index("form_templates_created_by_idx").using("btree", table.createdBy.asc().nullsLast().op("int8_ops")),
	index("form_templates_structure_gin_idx").using("gin", table.structure.asc().nullsLast().op("jsonb_ops")),
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [users.id],
			name: "form_templates_created_by_fkey"
		}),
]);

export const experimentRecords = pgTable("experiment_records", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "experiment_records_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	experimentId: bigint("experiment_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	formTemplateVersionId: bigint("form_template_version_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	userId: bigint("user_id", { mode: "number" }).notNull(),
	data: jsonb().notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("experiment_records_data_gin_idx").using("gin", table.data.asc().nullsLast().op("jsonb_path_ops")),
	index("experiment_records_experiment_id_idx").using("btree", table.experimentId.asc().nullsLast().op("int8_ops")),
	index("experiment_records_form_template_version_id_idx").using("btree", table.formTemplateVersionId.asc().nullsLast().op("int8_ops")),
	index("experiment_records_user_id_idx").using("btree", table.userId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.experimentId],
			foreignColumns: [experiments.id],
			name: "experiment_records_experiment_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.formTemplateVersionId],
			foreignColumns: [formTemplateVersions.id],
			name: "experiment_records_form_template_version_id_fkey"
		}),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "experiment_records_user_id_fkey"
		}).onDelete("cascade"),
]);

export const users = pgTable("users", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "users_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	name: text().notNull(),
	role: text().default('viewer').notNull(),
	email: text().notNull(),
	passwordHash: text("password_hash").notNull(),
	isActive: boolean("is_active").default(true).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	unique("users_email_key").on(table.email),
]);

export const laboratories = pgTable("laboratories", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "laboratories_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	name: text().notNull(),
	location: text(),
	capacity: integer(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const laboratoryMembers = pgTable("laboratory_members", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "laboratory_members_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	laboratoryId: bigint("laboratory_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	userId: bigint("user_id", { mode: "number" }).notNull(),
	role: text().default('member').notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("lab_members_laboratory_id_idx").using("btree", table.laboratoryId.asc().nullsLast().op("int8_ops")),
	index("lab_members_user_id_idx").using("btree", table.userId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.laboratoryId],
			foreignColumns: [laboratories.id],
			name: "laboratory_members_laboratory_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "laboratory_members_user_id_fkey"
		}).onDelete("cascade"),
	unique("laboratory_members_unique").on(table.laboratoryId, table.userId),
]);

export const experimentRecordFiles = pgTable("experiment_record_files", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "experiment_record_files_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	experimentRecordId: bigint("experiment_record_id", { mode: "number" }).notNull(),
	fileName: text("file_name").notNull(),
	mimeType: text("mime_type"),
	storageKey: text("storage_key").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	fileSizeBytes: bigint("file_size_bytes", { mode: "number" }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("erf_record_id_idx").using("btree", table.experimentRecordId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.experimentRecordId],
			foreignColumns: [experimentRecords.id],
			name: "experiment_record_files_experiment_record_id_fkey"
		}).onDelete("cascade"),
]);

export const experimentStatusHistory = pgTable("experiment_status_history", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "experiment_status_history_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	experimentId: bigint("experiment_id", { mode: "number" }).notNull(),
	status: text().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	changedBy: bigint("changed_by", { mode: "number" }),
	changedAt: timestamp("changed_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("experiment_status_history_experiment_id_idx").using("btree", table.experimentId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.experimentId],
			foreignColumns: [experiments.id],
			name: "experiment_status_history_experiment_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.changedBy],
			foreignColumns: [users.id],
			name: "experiment_status_history_changed_by_fkey"
		}),
]);

export const auditLogs = pgTable("audit_logs", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "audit_logs_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	userId: bigint("user_id", { mode: "number" }),
	action: text().notNull(),
	entityType: text("entity_type").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	entityId: bigint("entity_id", { mode: "number" }),
	metadata: jsonb(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("audit_logs_entity_idx").using("btree", table.entityType.asc().nullsLast().op("int8_ops"), table.entityId.asc().nullsLast().op("int8_ops")),
	index("audit_logs_user_id_idx").using("btree", table.userId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "audit_logs_user_id_fkey"
		}),
]);

export const resources = pgTable("resources", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "resources_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	laboratoryId: bigint("laboratory_id", { mode: "number" }).notNull(),
	type: text().notNull(),
	name: text().notNull(),
	status: text().default('available').notNull(),
	metadata: jsonb(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("resources_laboratory_id_idx").using("btree", table.laboratoryId.asc().nullsLast().op("int8_ops")),
	index("resources_type_idx").using("btree", table.type.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.laboratoryId],
			foreignColumns: [laboratories.id],
			name: "resources_laboratory_id_fkey"
		}).onDelete("cascade"),
]);

export const reservations = pgTable("reservations", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	id: bigint({ mode: "number" }).primaryKey().generatedAlwaysAsIdentity({ name: "reservations_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 9223372036854775807, cache: 1 }),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	resourceId: bigint("resource_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	userId: bigint("user_id", { mode: "number" }).notNull(),
	reservationDate: date("reservation_date").notNull(),
	startTime: time("start_time").notNull(),
	endTime: time("end_time").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("reservations_resource_id_idx").using("btree", table.resourceId.asc().nullsLast().op("int8_ops")),
	index("reservations_user_id_idx").using("btree", table.userId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.resourceId],
			foreignColumns: [resources.id],
			name: "reservations_resource_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "reservations_user_id_fkey"
		}).onDelete("cascade"),
	check("reservations_time_valid", sql`start_time < end_time`),
]);
